notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - oicr:S9k4EowgQv9AnbCfEZHSzCsg
sudo: required
services:
- docker

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.m2

language: java
jdk:
- oraclejdk8
install:
- docker version
- pip2.7 install --user setuptools==34.2.0
- pip2.7 install --user cwl-runner cwltool==1.0.20170217172322 schema-salad==2.2.20170222151604 avro==1.8.1
before_script:
- psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
- psql -c "ALTER USER dockstore WITH superuser;" -U postgres
- psql -c 'create database webservice_test with owner = dockstore;' -U postgres
- export PATH=$PATH:$PWD/dockstore-client/target

env:
   - EXTRA_MAVEN_VAR=""
   - EXTRA_MAVEN_VAR="cobertura:cobertura-integration-test coveralls:report"

script: ./scripts/run-tests.sh

before_install:
- pip install --upgrade pip
- mvn dependency:get -Dartifact=org.eluder.coveralls:coveralls-maven-plugin:4.2.0
- openssl aes-256-cbc -K $encrypted_3fcf447b96fd_key -iv $encrypted_3fcf447b96fd_iv -in dockstore-integration-testing/src/test/resources/secrets.tar.enc -out dockstore-integration-testing/src/test/resources/secrets.tar -d
- tar xvf dockstore-integration-testing/src/test/resources/secrets.tar



notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
